### ISSUE TITLE
Stop working after last huge update

### ISSUE THREAD

**Issue by serhii-londar** [odota/underlordsconstants#6]
I'm getting error while running data update:
```
(node:2391) UnhandledPromiseRejectionWarning: SyntaxError: VDF.parse: invalid syntax on line 3
    at Object.parse (/Users/serhiilondar/Documents/GitHub/underlordsconstants/node_modules/simple-vdf/index.js:40:19)
    at parseJson (/Users/serhiilondar/Documents/GitHub/underlordsconstants/tasks/updateconstants.js:227:25)
    at requestData (/Users/serhiilondar/Documents/GitHub/underlordsconstants/tasks/updateconstants.js:245:10)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:2391) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2391) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by mgmarlow** [comment]
Hey, I fixed this issue and opened a PR. See: https://github.com/odota/underlordsconstants/pull/7
